sudo: true
#dist: xenial
osx_image: xcode8

language: cpp

os:
  #- linux
  - osx

compiler:
  - gcc
  - clang

cache:
  
addons:
  apt:
    sources:
    
    packages: 

branches:
  #only:
    #- master
    
env:
  global:
    
  matrix:
    - USE_AVX=OFF
    - USE_AVX=ON
    
    
matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default
    - os: osx
      compiler: gcc

before_install:  

install:
  travis_wait 30 mvn install
  - bash -x .travis/install.sh
  
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd src;
      cmake -DUSE_AVX=$USE_AVX
            -DGPU=NONE .;
      ls ;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd src;
      cmake --trace -DUSE_AVX=$USE_AVX
                    -DGPU=NONE .;     
    fi
 
script:
  - make -j2

after_success:
  
