sudo: true
dist: xenial

language: cpp

branches:
  #only:
    #- master
    
matrix:
  include:
  - USE_AVX=OFF
  - USE_AVX=ON    
  - os: linux    
      compiler:
      - gcc
      - clang

before_install:  

install:   
  - bash -x .travis/install.sh
  
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd src;
      cmake -DUSE_AVX=$USE_AVX
            -DGPU=NONE .;
      ls ;
    fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cd src;
      cmake --trace -DUSE_AVX=$USE_AVX
                    -DGPU=NONE .;     
    fi
 
script:
  - make -j2

after_success:
  
